version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
     - pip install pytest
  build:
    commands:
      - python -m pytest tests/
cache:
  paths:
    - '/root/.m2/**/*'
